# server:
#   ssl:
#     key-store: classpath:keystore.p12
#     key-store-type: PKCS12
#     key-store-password: ssafyartrend

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/artrend?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
