spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    usernmae: sa
    password: "{cipher}AQDRiDG03QUvd3DLuNJo3TwWbFxvvbV3APIx7iCfXERPHJ0ZlnR3fpNfbcZl8vRkNplInbHUUMcO9UAJaT1yJRjJ5RLZt8sxhCzBYrxFoba7oPepaURBPqZsqLYeg75T2q+6b2AxStB1/MnXwYsgZ/2KL3fu9jcTNaNfDdJHewl/+BZVYNGLPxj/Q+NvIqUpzAqKVhauBZeCV2TrcLM6dDtux+phjTJ8EDuNTmzOKWl0n4jOkOwqXDZ4H6AJuX8hBdahDqkrmCKEswM0IVVl0yQDj8D+7rJnWlmGkL7xOnNQ9z7RcSLpQmZYU+0Zo1N7R2buuEdB/mTH6Au356QPkkqsRaO9Ure/gNTmhlhcIyMvJXbLbfbQXH2A1dvmvzuMVDg="

token:
  expiration_time: 864000000
  secret: "{cipher}AQB7TCY5Dvuukp//tcyY2MJ0TbADh9NEnHKQhynjDzMC/knk0gJKx619fQUSGDwxfQ+y+3LJCbPDnQl/DsfFT9u1vC2uVQA1d42Pcrx6qRQRjqVQoMJRqomtV4YwPKPOqB7XjHl3RCo8psvkuyl9QeyaudWljFSkM2WiZoQfGYtFckJDbzO6OLAMpUzaAPFXBtGY0m9oqLkRIViBBY8UU3cV4IoZ+sPjU0qSeUWJ5lwDA0GP/+ZWRXbBcS3sadgeF6ECSzW1wHbKlrkPtlRC3vx7uf3q6JNnbMcubneRSdnVRE8kM9ScvY0XhsNas2woiGrqpuvoyZ84ofxIOw372Hk8lr+35P5Rx8oe1XOANP3vTozR5ZO+c9tis1Py3Qv5wXSTDebcG18DK3WG5Re4oE4E"

gateway:
  ip: 192.168.0.177

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
